---
title: 'Class 6: R functions'
author: "Frank Lee"
date: "4/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Today we will focus on **R functions** but we will start with a bit of **file reading**.

```{r}
plot(1:10, typ="l", col="blue")
```

```{r}
read.table("test1.txt", header=TRUE, sep=",")
```

```{r}
read.delim("test2.txt", header=TRUE, sep="$")
```

```{r}
read.table("test3.txt")
```

```{r}
read.csv("https://bioboot.github.io/bggn213_S19/class-material/test1.txt")
```


## Our first function

Add some numbers

```{r}
add <- function(x, y=1) {
  # sum the input of x + y
  x + y
}
```

```{r}
add(4)
add (x=4, y=5)
add(4,5)
add(c(1,3,5), 1)
add(c(1,3,5))
# add(1,3,5)
# add(x=1, y="frank")
```

```{r}
rescale <- function(x) {
  rng <- range(x)
  (x-rng[1])/(rng[2]-rng[1])
}
```

```{r}
rescale(1:10)
```

```{r}
rescale( c(1, 3, NA, 5, 10))
```

```{r}
x <- c(1, 3, NA, 5, 10)  
rng <- range(x, na.rm = TRUE)
rng 
(x-rng[1])/(rng[2]-rng[1])

```

```{r}
rescale2 <- function(x, na.rm=TRUE) {
  rng <- range(x, na.rm=na.rm)
  (x-rng[1])/(rng[2]-rng[1])
}
```

```{r}
rescale2(c(1,3,NA, 10))
rescale2(c(1,3,NA,10), na.rm=FALSE)
```

```{r}
# rescale2(c(1,3,"barry", 10))
```


Another example

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=na.rm)
   } else {
     rng <-range(x)
   }
   print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   print("is it me you are looking for?")
   if(plot) {
     plot(answer, typ="b", lwd=4)
     print("Dont sing please!!!")
}
   print("I can see it in ...")
   
   # Return is usually at the end of the function because the code will stop
   return(answer)
}
```

```{r}
rescale3(1:10, plot=TRUE)
```







