---
title: "Find a Gene Project"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("bio3d")
```

```{r}
alignmentfasta <- read.fasta("musclerevised.fst")
alignmentfasta

```

```{r}
seqidentity(alignmentfasta)
seqs <- seqidentity(alignmentfasta)
seqs 
heatmap(seqs)
```

```{r}
old.par <- par()$mar

seqidentity(alignmentfasta)
heatmap(seqidentity(alignmentfasta), margins = c(8,5), symm=TRUE)


```


```{r}
consensus(alignmentfasta)
blast.pdb(consensus(alignmentfasta)$seq)
```



I should find the sequence with the highest identity to the other sequences based on the row-wise maximum sum from the sequence identity matrix

```{r}

# Add the sum of each row
sum.matrix <- rowSums(seqs)
sum.matrix

which.max(sum.matrix)


```

```{r}

alignmentfasta
alignmentfasta$ali[11,]
cat.fasta <- alignmentfasta$ali[11,]
cat.fasta[1:128]

blast.pdb(cat.fasta[1:128])
```

```{r}

pdb.annotate("5XXU_C")
pdb.annotate("3RH9_A")
pdb.annotate("6EUQ_A")
```


