CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Papio_anubis        HEG---------------------------------------------RTYRTTTGTPSA
Mouse               MISMASWQLLLLLCVATYGEPLAKVAPLVKPGSTGQQSGPQELVNAWEKESRYAESKPGS
Macaca_mulatta      MNSLVSWQLLLFLCATHFGEPLEKVASVENSRPTGQQLESLDLSAPWEQSLPCTERKPAA
Human               MNSLVSWQLLLFLCATHFGEPLEKVASVGNSRPTGQQLESLGLLAPGEQSLPCTERKPAA
Chimpanzee          MNSLVSWQLLLFLCATHFGEPLEEVASVGNSRPTGQQLESLGLLAPGEQSLPCTERKPAA
Sheep               MNVLLSRQLMLFLCATAFRETLENMAPMENPRTTGSQLGPATLRAPWEQSPRCAAGKPTA
Dog                 MNSLVSWQLMLLLCATSFRETLEKVAPMETPGPAGQRLGAQALPAPWERSP---------
Armadillo           MNSLVSWQLLLFLCATSFGETLTKVAPAENPRPTGQRLGPLAVLDPWEQSLRCEERKPSA
Dolphin             MNSLVSWQLMLFLCAVSFTETLEKATPMKNPRATGPRLRSPALLASGAQSPRCAERKPAV
Cheetah             MNSLVSWQLMLFLCATSFRETFEKVAPVENPLSTGQRLESQALLAPWEQSPRCAERKPTG
Cat                 MNSLVSWQLMLFLCATSFRETFEKVAPMENPLSTGQRLGSQALLAPWEQSPRCAERKPAG
Leopard             MNSLVSWQLMLFLCATSFRETFEKVAPMENPLSTGQRLGSQALLAPWEQSPRCAERKPAG
                                                                    .           

Papio_anubis        -----------CASASGRRYPR-----EPRQRRWAGLRAQVLGSELQTPEESQHVGRGGR
Mouse               -AGLRARRSSPCPPVEGPAGRQRP-LCASRSRLIPAPRGAVLVQREKDLSTYNWNSFGLR
Macaca_mulatta      TARLSRRGASLSSPAESSGSPQRRGLSAPSSRQIPAPQGAVLVQREKDLPNYNWNSFGLR
Human               TARLSRRGTSLSPPPESSGSPQQPGLSAPHSRQIPAPQGAVLVQREKDLPNYNWNSFGLR
Chimpanzee          TARLSRRGTSLSPPPESSGSPQQPGLSAPHSRQIPAPQGAVLVQREKDLPNYNWNSFGLR
Sheep               -AGPRPRGAALC-PSESSAGPRQPGPCAPRSRLIPAPRGAALVQREKDVSAYNWNSFGLR
Dog                 --------------------PR-----APQRHLMPARRGA-------DLPAYNWNVFGLR
Armadillo           -AGPSPRGPSLCAPPARPVAPQRPGLCAPRSRLIPAPRGAVLVQREKDPAAYNWNSFGLR
Dolphin             -AGP--RGASLCPPPESSAGPQLPGLCAPRSRLIPAPRGAVLVQREKDLSAYNWNSFGLR
Cheetah             -AQPNARGASLCPPPESAAGPQRPGLCAPRSRLIPAPRGAVLVQREKDLSTYNWNSFGLR
Cat                 -AQPNARGASLCPPPESAAGPQRPGLCAPRSRLIPAPRGAVLVQREKDLSAYNWNSFGLR
Leopard             -AQPNARGASLCPPPESASGPQRPGLCAPRSRLIPAPRGAVLVQREKDLSAYNWNSFGLR
                                         .      .  .  .. ..             :.   * *

Papio_anubis        RAKGGGTEPSN-----------PRQ-------
Mouse               YGRRQAARA-------------ARG-------
Macaca_mulatta      FGKREAVPPGAKAEAL------GGAEGAGAGQ
Human               FGKREAAPGNH-----------GRSAGRG---
Chimpanzee          FGKREAAPGNH-----------GRSAGRG---
Sheep               YGRRQAALPG------------GRGGARG---
Dog                 YGRRRAATPGLRGGTPSPRLRVPVGWGLGLRS
Armadillo           YGKRGAPLGSR-----------PRGAGRG---
Dolphin             YGKRHAAPPGSR----------GQGAGRG---
Cheetah             YGKRQTAP------------------------
Cat                 YGKRQTAP------------------------
Leopard             YGKRQTAP------------------------
                     ..                             
