CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Papio_anubis        -----------ELCNVSF---IASGWKVQCPLPSPCVLPAPHAVIPLGSEVHCPAPAPSA
mouse               MISMASWQLLLLLCVATYGEPLAKVAPLVKPGSTGQQSGPQELVNAWEKESRYAESKPGS
macaca_mulatta      MNSLVSWQLLLFLCATHFGEPLEKVASVENSRPTGQQLESLDLSAPWEQSLPCTERKPAA
human               MNSLVSWQLLLFLCATHFGEPLEKVASVGNSRPTGQQLESLGLLAPGEQSLPCTERKPAA
chimpanzee          MNSLVSWQLLLFLCATHFGEPLEEVASVGNSRPTGQQLESLGLLAPGEQSLPCTERKPAA
sheep               MNVLLSRQLMLFLCATAFRETLENMAPMENPRTTGSQLGPATLRAPWEQSPRCAAGKPTA
dog                 MNSLVSWQLMLLLCATSFRETLEKVAPMETPGPAGQRLGAQALPAPWERSP---------
Armadillo           MNSLVSWQLLLFLCATSFGETLTKVAPAENPRPTGQRLGPLAVLDPWEQSLRCEERKPSA
Dolphin             MNSLVSWQLMLFLCAVSFTETLEKATPMKNPRATGPRLRSPALLASGAQSPRCAERKPAV
Cheetah             MNSLVSWQLMLFLCATSFRETFEKVAPVENPLSTGQRLESQALLAPWEQSPRCAERKPTG
cat                 MNSLVSWQLMLFLCATSFRETFEKVAPMENPLSTGQRLGSQALLAPWEQSPRCAERKPAG
leopard             MNSLVSWQLMLFLCATSFRETFEKVAPMENPLSTGQRLGSQALLAPWEQSPRCAERKPAG
                                ** . :   : .      . .:     .     .   .          

Papio_anubis        ------------PPSASALAPGGTASRLPKRR----PK--------------EFQLFGRS
mouse               -AGLRARRSSPCPPVEGPAGRQRP-LCASRSRLIPAPRGAVLVQREKDLSTYNWNSFGLR
macaca_mulatta      TARLSRRGASLSSPAESSGSPQRRGLSAPSSRQIPAPQGAVLVQREKDLPNYNWNSFGLR
human               TARLSRRGTSLSPPPESSGSPQQPGLSAPHSRQIPAPQGAVLVQREKDLPNYNWNSFGLR
chimpanzee          TARLSRRGTSLSPPPESSGSPQQPGLSAPHSRQIPAPQGAVLVQREKDLPNYNWNSFGLR
sheep               -AGPRPRGAALC-PSESSAGPRQPGPCAPRSRLIPAPRGAALVQREKDVSAYNWNSFGLR
dog                 --------------------PR-----APQRHLMPARRGA-------DLPAYNWNVFGLR
Armadillo           -AGPSPRGPSLCAPPARPVAPQRPGLCAPRSRLIPAPRGAVLVQREKDPAAYNWNSFGLR
Dolphin             -AGP--RGASLCPPPESSAGPQLPGLCAPRSRLIPAPRGAVLVQREKDLSAYNWNSFGLR
Cheetah             -AQPNARGASLCPPPESAAGPQRPGLCAPRSRLIPAPRGAVLVQREKDLSTYNWNSFGLR
cat                 -AQPNARGASLCPPPESAAGPQRPGLCAPRSRLIPAPRGAVLVQREKDLSAYNWNSFGLR
leopard             -AQPNARGASLCPPPESASGPQRPGLCAPRSRLIPAPRGAVLVQREKDLSAYNWNSFGLR
                                                .  .     .              ::: **  

Papio_anubis        FPRA----------------------------
mouse               YGRRQAAR-----------------AARG---
macaca_mulatta      FGKREAVPPGAKAEA------LGGAEGAGAGQ
human               FGKREAAPGNH-----------GRSAGRG---
chimpanzee          FGKREAAPGNH-----------GRSAGRG---
sheep               YGRRQAALPG------------GRGGARG---
dog                 YGRRRAATPGLRGGTPSPRLRVPVGWGLGLRS
Armadillo           YGKR-GAPLGSR----------PRGAGRG---
Dolphin             YGKRHAAPPGSR----------GQGAGRG---
Cheetah             YGKRQTAP------------------------
cat                 YGKRQTAP------------------------
leopard             YGKRQTAP------------------------
                    : .                             
